name: Install Apigeelint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-apigeelint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Use Node.js version 18 or higher to satisfy dependencies

    - name: Install Apigeelint
      run: npm install -g apigeelint@2.12.0 --loglevel=error
      
    - name: Verify Installation
      run: |
        apigeelint --help || echo "Apigeelint installed successfully"
